### ISSUE TITLE
Adding new keyword to DSL to make permission inheritance easier

### ISSUE THREAD

**Issue by EgeAytin** [Permify/permify#188]
Let's elaborate this with an example; lets say we have relation of team in repository ( team is parent of repository). Now i want to give edit access to org.admin. Org is parent of project, project is parent of team. I want to maintain that access should be given to org.admin whose org is parent of a project whose child is the team of repository.

This can be achievable with giving action reference to actions. In this scenario, repository edit action looks and depends on team action which depends project and project also depends the rule org.admin.

```
entity user {}

entity organization {
    relation admin @user
    relation member @user
}
entity project {
    relation org @organization
    action edit = org.admin
}
entity team {
    relation project @project
    action edit = project.edit
}
entity repository {
    relation team @team
    action edit = team.edit
}
```

Although this solves the problem, defining action to inherit parent permission decreases readability (especially when nested hierarchies goes deeper) and giving to much power to the action keyword. For this specific nested hierarchies case, creating new keyword can be solve this.

**Comment by ioneyed** [comment]
I would be cautious of a hierarchy keyword that doesn't allow you to define a mapping (which you can do with the relationship syntax already) since the most explicit permission may need to apply and having an implicit relationship map could make it so that an project.admin can edit a repository when they were specifically set to a viewer on that repository.

There are many scenarios where the most explicit permission applies and the hierarchy may be ignored in those use cases. In this limited example it is harder to see those scenarios but in a multi-tenant SaaS style where the organization admin is most likely someone who is tasked to setup the account and do the billing, they may not need to get access all the way down implicitly.

Without knowing your thoughts on the new keyword or concerns on "action having too much power" I would suggest more documentation/scenarios/use cases before adding another keyword since it can be solved as it is today.

**Comment by tolgaOzen** [comment]
Hey @ioneyed, thank you for your thoughtful response. We appreciate your concerns about defining a new keyword for managing access control in nested hierarchies and agree that it may not be necessary.

As you pointed out, the most explicit permission should always apply, and having an implicit relationship map could cause unintended access control issues. We agree that documenting and providing more use cases for the current approach would be a more effective way to address the readability concerns that were raised.

Thank you for your valuable feedback, and please let us know if you have any other questions or concerns.
