### ISSUE TITLE
ABAC support 

### ISSUE THREAD

**Issue by EgeAytin** [Permify/permify#255]
Aim of that feature is being able to use policies and ABAC in Permify.

Requirements:

The user should be able to create a count-based policy.
Users should be able to create type and attribute-based policies.
The user should be able to create subscription policies.
The system should be an exertion to Permify which makes it possible to use OPA policies.
This should be included in Permify, and shouldn’t be downloaded later.

**Comment by leonard-henriquez** [comment]
@EgeAytin is ABAC planned on the roadmap?
Do you have a rough estimate?

**Comment by ioneyed** [comment]
> The system should be an exertion to Permify which makes it possible to use OPA policies.

Does this requirement mean that the policies could be written directly into Permify and it would act as the OPA server? Or rather that the attribute level permissions could be asserted using OPA since Permify could get to the field specific entities.

**Comment by tolgaOzen** [comment]
Hey @ioneyed ,This issue isn't really about using OPA policies in Permify. The system should extend Permify in a way that enables the use of OPA policies." It seems we may have miscommunicated our intentions. What we are considering in this issue is the inclusion of ABAC support while maintaining the logic of relationship-based access control. Our team is thoroughly examining the use cases to determine the precise implementation.
