### ISSUE TITLE
[BUG] Coverage Command Does Not Acknowledge Certain Relationships as Covered

### ISSUE THREAD

**Issue by tolgaOzen** [Permify/permify#810]
### Description
There's an inconsistency with the coverage command's behavior in recognizing defined relationships. For instance, when declaring a relationship with the format `product:{X}#manager@company:{Y}#manager`, it is expected that this relationship should not appear in the list of uncovered relationships. However, the current behavior of the system fails to recognize the relationship as covered.

### Expected Behavior
When the relationship ex. `product:{X}#manager@company:{Y}#manager` is defined, executing the coverage command should acknowledge this relationship as covered and it should not appear in the output of uncovered relationships.

### Current Behavior
Despite defining the relationship ex. `product:{X}#manager@company:{Y}#manager`, the coverage command still lists it as an uncovered relationship.

**Comment by ioneyed** [comment]
Interesting find on this issue:

If the `relationships` has any invalid relationship in it the relationship isn't covered occurs. However, once fixing the invalid relationship that is in the yml file, the coverage of relationships is also fixed.

I feel like a way to avoid this bug is to have the `permify coverage` command automatically run a `permify validate` so that if the schema is not valid, coverage is not ran.

I will get a sample schema that is reproducible for this issue but will take a little bit of time to make it non-sensitive.

**Comment by EgeAytin** [comment]
Closing this issue, https://github.com/Permify/permify/pull/928.
